# Generated by Django 2.2.19 on 2021-09-15 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_groups'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
    ]
