# Generated by Django 2.2.19 on 2021-09-15 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descrition',
            new_name='description',
        ),
    ]
